Repository ugr-sail/sinergym, pull requests merged in 2021-03, with the labels that each got.

#13 3 new weather files available
  README.md
  energym/__init__.py
  energym/data/buildings/5ZoneAutoDXVAV_AZ.idf
  energym/data/buildings/5ZoneAutoDXVAV_NY.idf
  energym/data/buildings/5ZoneAutoDXVAV_WA.idf
  energym/data/weather/USA_AZ_Tucson-Davis-Monthan.AFB.722745_TMY3.epw
  energym/data/weather/USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw
  energym/data/weather/USA_PA_Pittsburgh-Allegheny.County.AP.725205_TMY3.epw
  energym/data/weather/USA_WA_Port.Angeles-William.R.Fairchild.Intl.AP.727885_TMY3.epw
  energym/envs/__init__.py
  energym/envs/eplus_demo.py
  energym/envs/eplus_discrete.py
  setup.py
  test_env.py
Labels: enhancement

#14 Discrete environment improvements
  .gitignore
  README.md
  energym/data/buildings/5ZoneAutoDXVAV.idf
  energym/envs/eplus_discrete.py
  energym/utils.py
  images/weather_types.png
  requirements.txt
  setup.py
  test_env.py
Labels: documentation, enhancement

#15 Added examples folder and fixed observations
  energym/envs/eplus_discrete.py
  examples/test_mlflow.py
  examples/test_multiobs.py
Labels: bug, enhancement
