Repository ugr-sail/sinergym, pull requests merged in 2022-04, with the labels that each got.

#204 New Rule-Based Controllers
  docs/source/pages/controllers.rst
  docs/source/pages/usage-example.rst
  examples/DRL_usage.py
  examples/dqn_time_limit.py
  examples/rule_controller.py
  examples/time_limits.png
  examples/try_wrappers.py
  sinergym/__init__.py
  sinergym/utils/common.py
  sinergym/utils/controllers.py
  tests/test_controller.py
Labels: enhancement, Controller

#200 Sinergym 1.8.3 - year, month, day and hour in simulator output directly
  docs/source/pages/environments.rst
  examples/try_wrappers.py
  sinergym/data/variables/5ZoneAutoDXVAV_spaces.cfg
  sinergym/envs/eplus_env.py
  sinergym/simulators/eplus.py
  sinergym/utils/common.py
  sinergym/utils/controllers.py
  sinergym/utils/wrappers.py
  sinergym/version.txt
  tests/conftest.py
  tests/test_common.py
  tests/test_controller.py
  tests/test_simulator.py
Labels: enhancement, Testing, BackEnd, Env

#202 Sinergym 1.8.4 - Wrappers tests
  sinergym/utils/wrappers.py
  sinergym/version.txt
  tests/conftest.py
  tests/test_wrapper.py
Labels: bug, enhancement, Testing

#206 Fixed DRL_battery params and rewards
  DRL_battery.py
Labels: bug, enhancement, reward

#211 Changed evaluation callback model name to <experiment_name>.zip
  DRL_battery.py
  sinergym/utils/callbacks.py
Labels: bug, log
