Repository ugr-sail/sinergym, pull requests merged in 2023-04, with the labels that each got.

#320 (v2.3.0) - DatetimeWrapper, PreviousObservationWrapper and IncrementalWrapper
  codecov.yml
  docs/source/pages/modules/sinergym.utils.wrappers.DatetimeWrapper.rst
  docs/source/pages/modules/sinergym.utils.wrappers.DiscreteIncrementalWrapper.rst
  docs/source/pages/modules/sinergym.utils.wrappers.LoggerWrapper.rst
  docs/source/pages/modules/sinergym.utils.wrappers.MultiObjectiveReward.rst
  docs/source/pages/modules/sinergym.utils.wrappers.MultiObsWrapper.rst
  docs/source/pages/modules/sinergym.utils.wrappers.NormalizeObservation.rst
  docs/source/pages/modules/sinergym.utils.wrappers.OfficeGridStorageSmoothingActionConstraintsWrapper.rst
  docs/source/pages/modules/sinergym.utils.wrappers.PreviousObservationWrapper.rst
  docs/source/pages/modules/sinergym.utils.wrappers.rst
  docs/source/pages/wrappers.rst
  scripts/check_run_times.py
  sinergym/envs/eplus_env.py
  sinergym/utils/wrappers.py
  sinergym/version.txt
  tests/conftest.py
  tests/test_wrapper.py
Labels: wrapper

#328 (v2.3.1) Nested Wrappers Fix
  docs/source/pages/wrappers.rst
  examples/wrappers_examples.ipynb
  sinergym/utils/constants.py
  sinergym/utils/wrappers.py
  sinergym/version.txt
  tests/conftest.py
  tests/test_wrapper.py
Labels: wrapper

#330 Fix DatetimeWrapper sin and cos bug
  setup.py
  sinergym/utils/wrappers.py
Labels: bug

#331 (v2.3.2) - Multi version documentation fix
  .github/workflows/merge_pr.yml
  docs/source/pages/environments.rst
  docs/source/spelling_wordlist.txt
  setup.py
  sinergym/version.txt
Labels: bug, documentation

#333 Separate README.md installation section and add a list of tools which are using Sinergym
  INSTALL.md
  README.md
  docs/source/_templates/sinergym.html
  docs/source/index.rst
  docs/source/pages/installation.rst
  docs/source/pages/introduction.rst
  mlflowbuild.sh
  sinergym/version.txt
Labels: documentation, enhancement
