Repository ugr-sail/sinergym, pull requests merged in 2024-03, with the labels that each got.

#394 (v3.2.6) - Simulator callback to process actions update
  sinergym/simulators/eplus.py
  sinergym/version.txt
Labels: BackEnd

#397 (v3.2.7) - 5Zone building design improved for thermal control
  sinergym/data/buildings/5ZoneAutoDXVAV.epJSON
  sinergym/data/default_configuration/5ZoneAutoDXVAV.json
  sinergym/utils/constants.py
  sinergym/utils/controllers.py
  sinergym/version.txt
Labels: building

#402 (v3.2.9) Environment registration field bug
  sinergym/utils/common.py
  sinergym/version.txt
Labels: bug, Env
